# Generated by Django 4.2.4 on 2023-10-03 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp3', '0003_alter_contact_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
